# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Geospatial Artificial Intelligence
# Description of the Site
description: A proposal for an EPSRC/UKRI Centre for Doctoral Training
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: CDT proposal, Geospatial, Artificial Intelligence
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
# heroimage: https://images.pexels.com/photos/6153790/pexels-photo-6153790.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /assets/images/background.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: geo-ai@soton.ac.uk
questionnaire: https://tinyurl.com/geo-AI

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

contact_blurb: The development of this proposal is being lead by a diverse team of experienced academics from across the University. Click <a href="team">here</a> to find out more about us, or use the buttons below to drop us a message or fill out our industry-engagement questionnaire.
# Name of the Author
author-name: About
# URL for the Image of the Author
author-image: /assets/images/uos.png
# 60 Words About the Author
author-about: Geospatial data considers location-based information on objects, environments, events, and their trends. Applications span energy, agriculture, healthcare, transport, etc. Data-types are multiple, capturing diverse aspects at different resolutions and times, presenting huge interpretation challenges. <p>&nbsp;</p><a href="http://epsrc.ukri.org>">EPSRC</a> are expected to announce a call for new <a href="what_is">Centres for Doctoral Training (CDTs)</a> in the near future. At the <a href="http://www.southampton.ac.uk">University of Southampton</a> we are proposing a CDT which considers how AI can improve geospatial data and analysis in-line with non-academic partner needs, and how geospatial data can help answer fundamental AI questions. Cohorts will investigate the pipeline supporting intelligent policy and decisions, from data acquisition to generating actionable information by exploiting AI. Projects and training co-developed with partners will nurture the innovation, entrepreneurship, principles, and diverse perspectives needed to confront societal challenges of sustainability and inequality.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: team

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
